name 'openshiftops-openshift_zabbix'
version '0.1.0'
author 'Red Hat'
license 'ASL 2.0'
project_page 'https:/github.com/openshift/openshift_zabbix'
source 'https:/github.com/openshift/openshift_zabbix'
summary 'This module manages scripts used to enable Zabbix to monitor an OpenShift installation'
description 'This module manages scripts used to enable Zabbix to monitor an OpenShift installation'
dependency 'puppetlabs/stdlib', '>=2.2.0'
