#!/usr/bin/env oo-ruby

#   Copyright 2012 Red Hat Inc.
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
#
#  Purpose: Wrap the ActiveMQStats.java data collector, send its output to
#  Zabbix
#
#  Sample data output by ActiveMQStats.java:
#    heap_used         906872
#    heap_committed    26345472
#    nonheap_used      7074808
#    nonheap_committed 24313856
#    thread_count      8
#    queues            13
#

require 'benchmark'
require 'date'
require 'facter'

require_relative '../lib/zabbix_sender'
require_relative '../lib/utils/cli_opts'
require_relative '../lib/utils/log'

JAVA_HOME_DEFAULT = '/usr/lib/jvm/java'

if __FILE__ == $0
  cli = CLIOpts.new
  cli.on('-j', '--java-home PATH', String, 'JAVA_HOME path (default: /usr/lib/jvm/java)') { |x| cli.options[:java_home] = x }
  cli.parse
  opts = cli.options
  log  = Log.new
  java_home = opts[:java_home] || JAVA_HOME_DEFAULT

  unless File.exists?("#{File.dirname($0)}/ActiveMQStats.class")
    if File.exists?("#{java_home}/bin/javac")
      %x[#{java_home}/bin/javac -cp #{java_home}/lib/tools.jar ActiveMQStats.java]
    else
      log.error 'Unable to locate java class file and/or $JAVA_HOME/bin/javac. Exiting.'
      exit 1
    end
  end

  rval = %x[#{java_home}/bin/java -cp . ActiveMQStats].split("\n")

  zs = ZabbixSender.new(opts[:server], :port=>opts[:port], :log=>log)
  rval.each do |key_value|
    k,v = key_value.split
    zs.add_entry(k,v)
  end

  zs.send_data(opts[:verbose]) unless opts[:test]
end

__END__
