#!/usr/bin/env oo-ruby
#
#   Copyright 2012 Red Hat Inc.
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
#
# Purpose: report district capacity statistics to Zabbix.
#
require_relative '../lib/zabbix_sender'
require_relative '../lib/utils/log'
require_relative '../lib/utils/cli_opts'

load '/usr/sbin/oo-stats'

def get_district_stats
  begin
    stats = OOStats.new
    stats.gather_statistics
    return stats.results
  rescue => e
    $log.puts e.message
    $log.puts e.backtrace
  end

  return nil
end

def main
  # Initialize zabbix sender before oo-stats.  oo-stats stomps on
  # the facter library
  zs = ZabbixSender.new($opts[:server], :port=>$opts[:port], :log=>$log)

  stats = get_district_stats

  if stats.nil?
    $log.error "Unable to gather stats from oo-stats. Exiting..."
    exit
  end

  stats['profile_summaries'].each do |profile|
    name        = profile['profile']
    avail_gears = profile['effective_available_gears']
    avail_uids  = profile['dist_avail_uids']

    zs.add_entry("#{name}_district_capacity_uuids", avail_uids)
    zs.add_entry("#{name}_district_capacity_gears", avail_gears)

    if $opts[:verbose]
      $log.puts "#{name}: #{avail_gears} gears; #{avail_uids} uuids"
    end
  end

  zs.send_data($opts[:verbose]) unless $opts[:test]
end

if __FILE__ == $0
  cli = CLIOpts.new
  cli.parse
  $opts = cli.options
  $log  = Log.new
  main
end
